name: Build Package and Run Tests

on: [push]

defaults:
  run:
    shell: bash

jobs:
  unit_tests:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            pip_arg: ""
          - os: macos-10.15
            pip_arg: ""
          - os: windows-2019
            pip_arg: --user

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Pip Dependencies
      run: pip install ${{ matrix.pip_arg }} -r requirements.txt
    - name: Run Tests
      run: nosetests --with-coverage --cover-html --cover-package epformatline


